heat_template_version: 2015-04-30

description: Create cluster of monero mining worker nodes
  
parameters:
  network:
    type: string
    default: manuel
    description: external net name. use neutron net-list to figure it out.
  key_name:
    type: string
    description: ssh key required for server creation
  image_name:
    type: string
    description: image to use for the server
  flavor_name:
    type: string
    default: m1.medium
    description: openstack server flavor name use openstack flavor list to see options
  server_number:
    type: number
    description: number of server to spawn
    
resources:

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Port 22 and 16000 open for webserver.
      name: security-group
      rules: [
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: tcp,
        port_range_min: 22,
        port_range_max: 22},
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: tcp,
        port_range_min: 16000,
        port_range_max: 16000},
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: icmp}]

  server:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: server_number}
      resource_def:
        type: https://raw.githubusercontent.com/ciangottinim/heat-mining/master/server-template.yaml
        properties:
          server_name: mclus-%index%
          ssh_key_name: {get_param: key_name}
          server_image: {get_param: image_name}
          server_flavor: {get_param: flavor_name}
          network: {get_param: network}
          security_groups:
               - {get_resource: security_group}
