heat_template_version: 2015-04-30

description: >
  This is a nested stack that defines a single mining node. This stack is
  included by a ResourceGroup resource in the parent template.

parameters:

  server_image:
    type: string
    description: glance image used to boot the server

  server_flavor:
    type: string
    description: flavor to use when booting the server

  ssh_key_name:
    type: string
    description: name of ssh key to be provisioned on our server

  network:
   type: string
   description: Network id/nane

  server_name:
   type: string
  
  security_groups:
    type: comma_delimited_list

resources:

  server_eth0:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network }
      security_groups: {get_param: security_groups}
      replacement_policy: AUTO

  server:
    type: OS::Nova::Server
    properties:
      name: {get_param: server_name}
      image: {get_param: server_image}
      flavor: {get_param: server_flavor}
      key_name: {get_param: ssh_key_name}
      networks:
        - port: {get_resource: server_eth0}
      user_data_format: RAW
      user_data:
        |
        #!/bin/bash
        sysctl -w vm.nr_hugepages=128
        cd /home/ubuntu/xmr-stak-cpu/bin && ./xmr-stack-cpu &

outputs:

  server_ip:
    value: {get_attr: [server_eth0, fixed_ips, 0, ip_address]}

  server_id:
    value: {get_resource: server}
